# Generated by Django 5.2.13 on 2026-05-04 07:23

from django.db import migrations


def _rename_if_needed(schema_editor, from_table: str, to_table: str) -> None:
    """Rename physical table only when the new-style name exists and the legacy name does not."""
    connection = schema_editor.connection
    vendor = connection.vendor
    with connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = %s
                )
                """,
                [from_table],
            )
            has_from = cursor.fetchone()[0]
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = %s
                )
                """,
                [to_table],
            )
            has_to = cursor.fetchone()[0]
            if has_from and not has_to:
                cursor.execute(
                    'ALTER TABLE "%s" RENAME TO "%s";' % (from_table, to_table)
                )
        elif vendor == "sqlite":
            def _lit(n: str) -> str:
                return "'" + n.replace("'", "''") + "'"

            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name IN (%s, %s)"
                % (_lit(from_table), _lit(to_table))
            )
            names = {row[0] for row in cursor.fetchall()}
            if from_table in names and to_table not in names:
                cursor.execute(
                    "ALTER TABLE %s RENAME TO %s"
                    % (connection.ops.quote_name(from_table), connection.ops.quote_name(to_table))
                )


def rename_channel_tables_forwards(apps, schema_editor):
    _rename_if_needed(schema_editor, "slack_channels_channel", "channels_channel")
    _rename_if_needed(schema_editor, "slack_channels_channelmembership", "channels_channelmembership")


def rename_channel_tables_backwards(apps, schema_editor):
    _rename_if_needed(schema_editor, "channels_channel", "slack_channels_channel")
    _rename_if_needed(schema_editor, "channels_channelmembership", "slack_channels_channelmembership")


class Migration(migrations.Migration):

    dependencies = [
        ("slack_channels", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_channel_tables_forwards, rename_channel_tables_backwards),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="channel",
                    table="channels_channel",
                ),
                migrations.AlterModelTable(
                    name="channelmembership",
                    table="channels_channelmembership",
                ),
            ],
        ),
    ]
