# Generated by Django 5.2.13 on 2026-05-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack_channels", "0002_use_legacy_channel_table_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmembership",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
