# Generated by Django 5.2.13 on 2026-05-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_message_channel_created_at_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="chat_messag_channel_2777f8_idx",
            old_name="chat_messages_channel_created_idx",
        ),
    ]
