# Generated by Django 5.2.13 on 2026-05-01 04:10

from django.db import migrations, models

import backend.apps.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("user_id", models.BigAutoField(db_column="user_id", primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("nickname", models.CharField(blank=True, default="", max_length=50)),
                ("password", models.CharField(db_column="password_hash", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "AppUser",
            },
            managers=[
                ("objects", backend.apps.accounts.models.AppUserManager()),
            ],
        ),
    ]
