# Generated by Django 5.2.13 on 2026-05-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[],
        ),
    ]
